name = "localhost-1313"
compatibility_date = "2025-01-01"
pages_build_output_dir = "."

[vars]
REF_URL = "https://serffigxjssvpeo.help/RC2TZM?sub_id_3=localhost%3A1313"
HMAC_KEY = "5146f5ce1bc773dee0179009ccb437a90c7deb1509f268a5d2c9f94fb1faddb2"
COOKIE_NAME = "mi5"
PLAY_PATH = "join-now"
BUTTON_ID = "p473e39fdeee640c3df47714e33b41874"
GATE_SALT = "a8efa36f51e059ef"
GO_URLS = "[\"https://monitorre.top/go/ref\", \"https://firespot.click/go/ref\", \"https://fintechfox.click/go/ref\", \"https://buffout.click/go/ref\"]"
GO_TOKEN = "6c27a2676e6fb97970145a1c9daa1d717ea137c80518a24c"
GO_COOKIE = "lft5"
CTA_SELECTOR = ".play-button"
